# -*- coding: utf-8 -*-
"""
Created on Fri Nov 26 02:59:13 2021

@author: gabriel
"""

# -*- coding: utf-8 -*-
"""Mineração em Redes Heterogêneas - Exemplos de Network Embedding usando Autoencoders.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z6JoVAfCXiJQXWSWuVGpEL5Vggty8wWc

# Structural Deep Network Embedding (SDNE)

## Baixando e instalando bibliotecas
"""

!git clone https://github.com/shenweichen/GraphEmbedding

!pip install tensorflow==1.4.0

!cd GraphEmbedding; python setup.py install

!mv GraphEmbedding/* .

"""# Carregando uma Rede de Informação"""

import networkx as nx
G = nx.read_edgelist('data/wiki/Wiki_edgelist.txt',create_using=nx.DiGraph(),nodetype=None,data=[('weight',int)])#read graph

"""# Definindo a topologia do Autoencoder do SDNE"""

from ge import SDNE
model = SDNE(G,hidden_size=[256,128,64,32,16,2]) #init model

"""# Treinando o modelo"""

model.train(batch_size=3000,epochs=10,verbose=2)# train model

"""# Obtendo as Embeddings de cada nós da rede"""

embeddings = model.get_embeddings()# get embedding vectors

embeddings